_wandb:
    value:
        cli_version: 0.22.3
        e:
            gcvylcxhoirpvug60rg00odyk6aupfj5:
                codePath: openai_finetune.py
                codePathLocal: openai_finetune.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1004769636352"
                        used: "914339672064"
                email: christian.cooper.us@gmail.com
                executable: C:\Python312\python.exe
                git:
                    commit: 08fdbcf851703bf75c66a3469132b32db6611284
                    remote: https://github.com/HarleyCoops/StoneyNakoda.git
                host: PC
                memory:
                    total: "16749838336"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\chris\StoneyNakoda\openai_finetune.py
                python: CPython 3.12.6
                root: C:\Users\chris\StoneyNakoda
                startedAt: "2025-10-29T11:25:27.628418Z"
                writerId: gcvylcxhoirpvug60rg00odyk6aupfj5
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 49
                - 95
                - 105
            "2":
                - 49
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.6
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-arm64
base_model:
    value: gpt-4.1-2025-04-14S
train_file:
    value: C:\Users\chris\StoneyNakoda\OpenAIFineTune\stoney_train.jsonl
valid_file:
    value: C:\Users\chris\StoneyNakoda\OpenAIFineTune\stoney_valid.jsonl
